### ISSUE TITLE
No audio on the main Alex Jones Show Item or War Room

### ISSUE THREAD

**Issue by ilikenwf** [Powersurge/banned.video#2]
Is this just happening to me or is it also happening to all of oyu too?

**Comment by Powersurge** [comment]
I had my developer look at it and he is working on a fix at the moment. The issue is with the m3u8 file served by Banned.Video. The file has two audio streams, one of which works and the other doesn't. Currently, the file is setting both audio streams as the "default" stream, which is incorrect. As a result, we see video, but no audio in Kodi. We do not have any control over the Kodi player to change audio stream. Since the issue is with the m3u8 file being served by Banned.Video, the only way to make the Banned.Video addon work for now is to create a temporary m3u8 file and have the addon use that until Banned.Video fixes the m3u8 file that they are serving.

**Comment by ilikenwf** [comment]
Ah, interesting and good to know.

I guess your dev could automate the process and have it generate an m3u8
every time you choose a stream if there's a way of deriving which audio
stream is the bad one?

Thanks for paying for this, I should have got off my lazy butt sooner
and tried to fix it for us both. By the way, is this being hosted on any
repos yet?

**Comment by Powersurge** [comment]
Your welcome! I was tired of waiting for the Infowars addon to get updated and bugs fixed. Then I discovered that it was abandoned and that is what made me decide to hire a developer to work on this. If I knew how to code in Python, then I would have no problem adding this addon to the Kodi repository, but I can't be a maintainer because it would take too long for me to fix issues like this one and the users would get upset with issues taking me months to get resolved (plus I can't afford it). Do you know how to code in Python? If so, feel free to fork this project and [add it to the Kodi repository](https://kodi.wiki/view/Submitting_Add-ons) if you want.

**Comment by ilikenwf** [comment]
Interesting - I tend to just use the live shows stream but if I get in the mood I'll try to take a look sometime. I've had a lazy streak as of late.

**Comment by ilikenwf** [comment]
So this got posted on 4chan, a new playlist link for infowars?

Audio seems better on this for live...may be worth seeing if the other shows are on this path too.

https://freespeech.akamaized.net/hls/live/2016712/live1/playlist.m3u8

**Comment by ilikenwf** [comment]
Apparently not new...maybe IW fixed the m3u...

**Comment by ilikenwf** [comment]
My latest PR should fix this.
